/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package layout.com.squareup.leakcanary;

public final class R {
    public static final class drawable {
        public static final int leak_canary_icon = 0x7f070068;
        public static final int leak_canary_notification = 0x7f070069;
        public static final int leak_canary_toast_background = 0x7f07006a;
    }
    public static final class id {
        public static final int leak_canary_action = 0x7f080070;
        public static final int leak_canary_display_leak_failure = 0x7f080071;
        public static final int leak_canary_display_leak_list = 0x7f080072;
        public static final int leak_canary_row_connector = 0x7f080073;
        public static final int leak_canary_row_more = 0x7f080074;
        public static final int leak_canary_row_text = 0x7f080075;
        public static final int leak_canary_row_time = 0x7f080076;
    }
    public static final class layout {
        public static final int leak_canary_display_leak = 0x7f0a0034;
        public static final int leak_canary_heap_dump_toast = 0x7f0a0035;
        public static final int leak_canary_leak_row = 0x7f0a0036;
        public static final int leak_canary_ref_row = 0x7f0a0037;
        public static final int leak_canary_ref_top_row = 0x7f0a0038;
    }
    public static final class string {
        public static final int leak_canary_analysis_failed = 0x7f0c003a;
        public static final int leak_canary_class_has_leaked = 0x7f0c003b;
        public static final int leak_canary_could_not_save_text = 0x7f0c003c;
        public static final int leak_canary_could_not_save_title = 0x7f0c003d;
        public static final int leak_canary_delete = 0x7f0c003e;
        public static final int leak_canary_delete_all = 0x7f0c003f;
        public static final int leak_canary_delete_all_leaks_title = 0x7f0c0040;
        public static final int leak_canary_display_activity_label = 0x7f0c0041;
        public static final int leak_canary_excluded_row = 0x7f0c0042;
        public static final int leak_canary_failure_report = 0x7f0c0043;
        public static final int leak_canary_leak_excluded = 0x7f0c0044;
        public static final int leak_canary_leak_list_title = 0x7f0c0045;
        public static final int leak_canary_no_leak_text = 0x7f0c0046;
        public static final int leak_canary_no_leak_title = 0x7f0c0047;
        public static final int leak_canary_notification_channel = 0x7f0c0048;
        public static final int leak_canary_notification_message = 0x7f0c0049;
        public static final int leak_canary_permission_not_granted = 0x7f0c004a;
        public static final int leak_canary_permission_notification_text = 0x7f0c004b;
        public static final int leak_canary_permission_notification_title = 0x7f0c004c;
        public static final int leak_canary_share_heap_dump = 0x7f0c004d;
        public static final int leak_canary_share_leak = 0x7f0c004e;
        public static final int leak_canary_share_with = 0x7f0c004f;
        public static final int leak_canary_storage_permission_activity_label = 0x7f0c0050;
        public static final int leak_canary_toast_heap_dump = 0x7f0c0051;
    }
    public static final class style {
        public static final int leak_canary_LeakCanary_Base = 0x7f0d0187;
        public static final int leak_canary_Theme_Transparent = 0x7f0d0188;
    }
}
